### PR TITLE
add support for new resource

### PR DESCRIPTION
**Pull request by alexpop**
### 03-building_custom_resources.pptx

Modified a lot of the slides in order to use the latest custom resources framework introduced in chef-client 12.5. Please review my changes slide by slide

### 02-fundamentals_refresher.pptx

Added slide 13(Exercise: Download knife.rb)

Updated slide 21("Bootstrap" the Target Instance) to use chef-client 12.5.1 and show the same version in the output

Slides 24-29(knife bootstrap) updated to reflect the flow of validatorless bootstrapping

Updated other slides where chef-client 12.3.0 was showing with 12.5.1

### Handbook requires updates for:
  resource code
  bootstrap version
  -P in the boostrap command contains an invalid - character

### CODE REVIEW

**Comment by burtlo** [comment]
Reviewing this now.

**Comment by burtlo** [comment]
This looks great. Thanks for adding the changes to include the new resources functionality.

**Comment by alexpop** [comment]
Thanks Frank, what do we do with the handbook? That needs an update also to reflect the resource changes, chefspec, etc

**Comment by burtlo** [comment]
@alexpop You're right. Would you open an issue related to that so that we can address it.

**Pull request merged**
