### PR TITLE
Changed chefspec section to use apache as an example instead of mailx.

### PR DESCRIPTION
**Pull request by johnfitzpatrick**
Changed chefspec section to use apache as an example instead of mailx, as the chef_handlers section that included mailx has been changed to use create a file instead of using email

### CODE REVIEW

**Comment by burtlo** [comment]
File path appears to be formatted poorly.

**Comment by burtlo** [comment]
Explicit action is not required.

**Comment by burtlo** [comment]
Changing things over to test the apache cookbook leaves a lot of recipe untested. Namely it leaves the custom resource and the service untested which is requires more work and more examples for the learner to be shown.

I would love to see this section test the entire apache recipe before we use this for core Chef Intermediate courses.

**Comment by johnfitzpatrick** [comment]
I didnt alter those two slides 'Exercise: Write a Real Test' and 'Exercise: Update Original Recipe' in this review, so those fixes would need to be implemented in the master branch.

If the instructor uses the '06-implementing_chef_handlers-file_handler' section then the mailx cookbook doesn't exist on their system, so they cannot complete that part of the Chefspec lab.  So if the  alternative '06-implementing_chef_handlers-file_handler' section is kept as an alternative, then I reckon the Apache version of chefspec should remain to complement it.  Testing custom resources should definately be included, even as a discussion item without lab, or at least we shouldn't totally avoid, and have some instructor notes, it as its always bound to come up.

**Pull request merged**
