### PR TITLE
First draft of Signing Up for a Hosted Chef Account

### PR DESCRIPTION
**Pull request by SteveDelFante**
:construction: 

@burtlo Here is my first draft.

### CODE REVIEW

**Comment by burtlo** [comment]
Delete all the introduction slides from it.

screen shot 2015-06-05 at 1 58 42 pm

Delete all the closing slides.

screen shot 2015-06-05 at 1 59 13 pm

Delete all the extraneous sections

screen shot 2015-06-05 at 1 59 43 pm

It seems strange that they they are different sizes. What is circled there - why should the learner look there?

screen shot 2015-06-05 at 2 01 40 pm

For this deck I want the user to reset / download their user key.

screen shot 2015-06-05 at 2 02 54 pm

**Comment by SteveDelFante** [comment]
So no need for the slide that asks them to look at their org to ensure it was created? I'll delete that entire slide?

**Comment by burtlo** [comment]
Leave that slide. The circled area wasn't clear to me at first that you were asking me to look at the new organization.

**Comment by SteveDelFante** [comment]
Where do you see this?

extraneous sections

**Comment by burtlo** [comment]
It's perhaps the Mac version. See if you can find sections in your version and see if you can display them. If not, don't worry, I'll remove them.

**Comment by burtlo** [comment]
Looks like you have two commits. Both of the commits have the same name. They also both are missing a description. The body of the commit is useful for those of us working with the content.

**Comment by SteveDelFante** [comment]
I would like to learn how to resolve the duplicate commit names

**Comment by burtlo** [comment]
When you commit changes in the future be mindful of it. In this instance I would leave it.

**Pull request merged**
