### PR TITLE
refreshed chefspec slides

### PR DESCRIPTION
**Pull request by alexpop**
* Deleted slides
 - 7(Exercise: Make a 'spec' Directory)
 - 26(Exercise: Make a 'spec' Directory)

 because `rspec --init` creates a generic 1 page rspec helper that needs to be cleared.

When the `motd` cookbook will be created using `chef generate cookbook`, the spec and helper files will exist already 

---

* Replaced on all slides containing ChefSpec this code:
```
  let(:chef_run) { ChefSpec::SoloRunner.converge(described_recipe) }
```
with:
```
  let(:chef_run) do
    runner = ChefSpec::ServerRunner.new
    runner.converge(described_recipe)
  end
```

to support server level features in chefspec. This is the same code used by the generated recipe test when `chef generate cookbook` is used.

---

* In slides 
 - 8(Exercise: Create a Spec Helper)
 - 27(Exercise: Create a Spec Helper), I replaced:

```
ChefSpec::Coverage.start!
```
with:
```
at_exit { ChefSpec::Coverage.report! }
```

in order to present the user friendly `ChefSpec Coverage report` at the end of the rspec run. It's used by the top community cookbooks.

### CODE REVIEW

**Comment by burtlo** [comment]
What version of ChefSpec are you using:

```
at_exit { ChefSpec::Coverage.report! }
``` 

was replaced with 

```
ChefSpec::Coverage.start!
```

**Comment by burtlo** [comment]
```
rspec --init
```
It generates the **spec** folder and the **spec_helper** file, and a **.rspec** file all in one command.

I know that it is not perfect because the **spec_helper.rb** contains lots of comments but it doesn't hurt.

**Comment by burtlo** [comment]
The **motd** cookbook already exists within the chef-repo so it doesn't have the luxury of being generated with that content. However, we can of course update that repo so that it does have that content already in place.

This would also mean that we should change all the references to creating a cookbook to use the new `chef generate cookbook`. That would be the handlers section.

**Comment by burtlo** [comment]
I definitely like the change to use the ServerRunner.

**Comment by alexpop** [comment]
Ok, thanks for reviewing. I rolled back the slides to use  `ChefSpec::Coverage.start!`

Do you want `rspec --init` back in?

**Comment by burtlo** [comment]
:heart:

**Pull request merged**
